apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: devops-starter-kit-pdb
  namespace: devops-starter-kit
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: devops-starter-kit-app
